presubmits:  
  kubernetes/test-infra:
  - name: pull-test-infra-bazel-canary
    always_run: false
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:latest-experimental
        imagePullPolicy: Always
        args:
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--service-account=/etc/service-account/service-account.json"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--scenario=kubernetes_execute_bazel"
        - "--timeout=15"
        - "--" # end bootstrap args, scenario args below
        - "hack/build-then-unit.sh"
        volumeMounts:
        resources:
          requests:
            memory: "2Gi"

# Testing to make sure things still update.
periodics:
  - interval: 10m
    name: ci-test-infra-canary-echo-test
    decorate: true
    spec:
      containers:
        - image: alpine
          command: ["/bin/date"]

  - name: ci-test-infra-benchmark-demo
    interval: 20m
    decorate: true
    extra_refs:
    - org: cjwagner
      repo: test-infra
      base_ref: microbe-nchmarks
    spec:
      containers:
      - image: golang:latest
        command:
        - go
        args:
        - run
        - ./pkg/benchmarkjunit
        - --log-file=$(ARTIFACTS)/benchmark-log.txt
        - --output=$(ARTIFACTS)/junit_benchmarks.xml
        - ./experiment/dummybenchmarks/...
